import { useEffect } from 'react';

export default function Documentation({ open, onClose }) {
  useEffect(() => {
    if (!open) return undefined;
    function onKey(e) { if (e.key === 'Escape') onClose(); }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div className="docs-overlay" onClick={onClose}>
      <div
        className="docs-panel"
        role="dialog"
        aria-modal="true"
        aria-label="Project structure documentation"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="docs-head">
          <h2>Project structure &amp; requirements</h2>
          <button type="button" className="docs-close" onClick={onClose} aria-label="Close">×</button>
        </div>

        <div className="docs-scroll">
          <section className="docs-section">
            <h3>Two project types are accepted</h3>
            <p>
              Detected automatically from what's at the root of the archive — no flag to set, no
              picker to choose from.
            </p>
            <div className="docs-cards">
              <div className="docs-card">
                <div className="docs-card-title"><span className="docs-dot docs-dot-copper" />Web project (Capacitor)</div>
                <p>A React/Vite/etc. project with a <code>package.json</code> at the root. Wrapped
                  into an Android shell with Capacitor at build time.</p>
                <ul>
                  <li><code>package.json</code> — required, at the root</li>
                  <li>A build script npm can run (e.g. <code>vite build</code>) that produces a
                    static output directory</li>
                  <li>Optional: a <code>capacitor.config.json/.ts</code> — reused as-is if present
                    instead of being overwritten</li>
                </ul>
              </div>
              <div className="docs-card">
                <div className="docs-card-title"><span className="docs-dot docs-dot-violet" />Native Android (Gradle)</div>
                <p>A Kotlin/Java project built directly by its own Gradle wrapper — no Capacitor
                  or web step involved at all.</p>
                <ul>
                  <li><code>settings.gradle</code> or <code>settings.gradle.kts</code> — required, at the root</li>
                  <li><code>build.gradle</code> or <code>build.gradle.kts</code> — required, at the root</li>
                  <li>Complete Gradle wrapper, all four files:
                    <code>gradlew</code>, <code>gradlew.bat</code>,
                    <code>gradle/wrapper/gradle-wrapper.jar</code>,
                    <code>gradle/wrapper/gradle-wrapper.properties</code>
                  </li>
                </ul>
              </div>
            </div>
          </section>

          <section className="docs-section">
            <h3>Not allowed</h3>
            <ul className="docs-flat-list">
              <li>A top-level <code>android/</code>, <code>ios/</code>, or <code>platforms/</code>
                folder — these are generated by the build itself and can't be safely merged with
                an existing one, so an archive containing one is rejected outright.</li>
              <li>Path traversal or absolute paths inside the archive (e.g. <code>../../etc</code>)
                — rejected as unsafe.</li>
              <li>An empty archive, or one with neither marker file at the root.</li>
            </ul>
          </section>

          <section className="docs-section">
            <h3>Single wrapper folder? No problem</h3>
            <p>
              If the whole zip is one top-level folder (the common "Download ZIP" shape from
              GitHub), it's automatically flattened as long as that folder itself looks like a
              project root — everything inside it moves up a level before validation runs.
            </p>
          </section>

          <section className="docs-section">
            <h3>Allowed file types</h3>
            <p>Anything else in the archive is silently skipped, not rejected — only these are
              trusted to build the app itself:</p>
            <div className="docs-ext-grid">
              <ExtGroup label="Web source" items=".js .jsx .ts .tsx .mjs .cjs .json .css .scss .sass .less .html .htm" />
              <ExtGroup label="Native Android source" items=".kt .kts .java .gradle .xml .pro .properties .aidl" />
              <ExtGroup label="Assets" items=".svg .png .jpg .jpeg .gif .webp .ico .woff .woff2 .ttf .eot" />
              <ExtGroup label="Media" items=".mp4 .webm .mov .mp3 .wav .ogg .m4a .pdf" />
              <ExtGroup label="Misc" items=".md .txt .gitignore .npmrc .yml .yaml .lock" />
              <ExtGroup label="By exact filename" items="LICENSE README Dockerfile .env.example gradlew gradlew.bat gradle-wrapper.jar gradle-wrapper.properties" />
            </div>
          </section>

          <section className="docs-section">
            <h3>Limits</h3>
            <ul className="docs-flat-list">
              <li>300&nbsp;MB max archive size by default (deployment-configurable).</li>
              <li>Builds run in an isolated, disposable container per job — capped CPU/memory,
                destroyed after each build.</li>
              <li>Android permissions are only ever added if you check them in the confirmation
                popup that appears after you pick a file — an untouched selection builds the
                manifest exactly as the project already declares it.</li>
            </ul>
          </section>
        </div>
      </div>
    </div>
  );
}

function ExtGroup({ label, items }) {
  return (
    <div className="docs-ext-group">
      <div className="docs-ext-label">{label}</div>
      <div className="docs-ext-items">
        {items.split(' ').map((it) => <code key={it}>{it}</code>)}
      </div>
    </div>
  );
}
