'use strict';

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

class ValidationError extends Error {}

const FORBIDDEN_TOP_LEVEL = new Set([
  'android', 'ios', 'platforms', 'capacitor.config.json', 'capacitor.config.ts',
]);

// Only these file types are trusted to build the web app itself. Anything
// else in the archive (native-platform config like proguard-rules.pro,
// editor/OS cruft, license files, whatever) is simply skipped rather than
// failing the whole upload — none of it is needed to build the APK, since
// the native android/ project is generated fresh every build regardless of
// what was in the zip.
const ALLOWED_EXTENSIONS = new Set([
  '.js', '.jsx', '.ts', '.tsx', '.json', '.css', '.scss', '.sass', '.less',
  '.html', '.htm', '.md', '.mjs', '.cjs', '.svg', '.png', '.jpg', '.jpeg',
  '.gif', '.webp', '.ico', '.woff', '.woff2', '.ttf', '.eot', '.txt',
  '.gitignore', '.npmrc', '.yml', '.yaml', '.lock',
  // Media assets — common in real-world apps (splash videos, sound effects,
  // etc.) and otherwise silently dropped, which just trades a build failure
  // for a broken-looking app.
  '.mp4', '.webm', '.mov', '.mp3', '.wav', '.ogg', '.m4a', '.pdf',
]);

// Filenames (not extensions) that are also fine to skip past — no extension,
// or an extension that's ambiguous/misleading outside this specific name.
// path.extname('.env.example') is '.example', not '.env.example' (Node
// treats the part after the first dot in a dotfile as the "name"), so an
// entry in ALLOWED_EXTENSIONS for '.env.example' would never actually
// match anything — matching on the full basename here is the correct fix.
const ALLOWED_BASENAMES = new Set([
  'license', 'license.md', 'license.txt', 'readme', 'dockerfile',
  '.env.example', '.env.sample',
]);

function isSafeEntryName(name) {
  // Reject absolute paths, zip-slip traversal, and null bytes.
  if (name.includes('\0')) return false;
  const normalized = path.normalize(name);
  if (normalized.startsWith('..') || path.isAbsolute(normalized)) return false;
  return true;
}

function isAllowedFile(entryName) {
  const base = path.basename(entryName).toLowerCase();
  if (ALLOWED_BASENAMES.has(base)) return true;
  const ext = path.extname(entryName).toLowerCase();
  return !ext || ALLOWED_EXTENSIONS.has(ext);
}

function validateAndExtract(zipPath, destDir) {
  const zip = new AdmZip(zipPath);
  const entries = zip.getEntries();

  if (entries.length === 0) {
    throw new ValidationError('The archive is empty.');
  }

  let hasPackageJson = false;
  const skipped = [];
  const toExtract = [];

  for (const entry of entries) {
    const entryName = entry.entryName.replace(/\\/g, '/');

    if (!isSafeEntryName(entryName)) {
      throw new ValidationError(`Unsafe path in archive: ${entryName}`);
    }

    const parts = entryName.split('/').filter(Boolean);
    const topLevel = parts[0] ? parts[0].toLowerCase() : '';

    if (FORBIDDEN_TOP_LEVEL.has(topLevel)) {
      throw new ValidationError(
        `Archive already contains "${parts[0]}". Upload a plain React project — native platform folders are generated by the build.`
      );
    }

    if (entryName === 'package.json' || entryName.endsWith('/package.json')) {
      // Only trust a package.json at the project root (depth 0 or 1 if the
      // zip wraps everything in a single top folder).
      if (parts.length <= 2) hasPackageJson = true;
    }

    if (entry.isDirectory) {
      toExtract.push(entry);
      continue;
    }

    if (isAllowedFile(entryName)) {
      toExtract.push(entry);
    } else {
      skipped.push(entryName);
    }
  }

  if (!hasPackageJson) {
    throw new ValidationError('No package.json found at the project root.');
  }

  fs.mkdirSync(destDir, { recursive: true });
  for (const entry of toExtract) {
    zip.extractEntryTo(entry, destDir, true, true);
  }

  // If the zip wrapped everything in a single top-level folder, flatten it
  // so package.json ends up directly inside destDir.
  const rootEntries = fs.readdirSync(destDir);
  if (rootEntries.length === 1) {
    const onlyPath = path.join(destDir, rootEntries[0]);
    if (fs.statSync(onlyPath).isDirectory() && fs.existsSync(path.join(onlyPath, 'package.json'))) {
      for (const child of fs.readdirSync(onlyPath)) {
        fs.renameSync(path.join(onlyPath, child), path.join(destDir, child));
      }
      fs.rmSync(onlyPath, { recursive: true, force: true });
    }
  }

  if (!fs.existsSync(path.join(destDir, 'package.json'))) {
    throw new ValidationError('package.json not found after extraction.');
  }

  return { skipped };
}

module.exports = { validateAndExtract, ValidationError };
