'use strict';

const fs = require('fs');
const path = require('path');
const AdmZip = require('adm-zip');

class ValidationError extends Error {}

const FORBIDDEN_TOP_LEVEL = new Set([
  'android', 'ios', 'platforms', 'capacitor.config.json', 'capacitor.config.ts',
]);

// Only allow project-source-like file extensions through. Anything else in
// the archive causes rejection rather than silent stripping, so the user
// knows exactly why a build was refused.
const ALLOWED_EXTENSIONS = new Set([
  '.js', '.jsx', '.ts', '.tsx', '.json', '.css', '.scss', '.sass', '.less',
  '.html', '.htm', '.md', '.mjs', '.cjs', '.svg', '.png', '.jpg', '.jpeg',
  '.gif', '.webp', '.ico', '.woff', '.woff2', '.ttf', '.eot', '.txt',
  '.env.example', '.gitignore', '.npmrc', '.yml', '.yaml', '.lock',
]);

function isSafeEntryName(name) {
  // Reject absolute paths, zip-slip traversal, and null bytes.
  if (name.includes('\0')) return false;
  const normalized = path.normalize(name);
  if (normalized.startsWith('..') || path.isAbsolute(normalized)) return false;
  return true;
}

function validateAndExtract(zipPath, destDir) {
  const zip = new AdmZip(zipPath);
  const entries = zip.getEntries();

  if (entries.length === 0) {
    throw new ValidationError('The archive is empty.');
  }

  let hasPackageJson = false;

  for (const entry of entries) {
    const entryName = entry.entryName.replace(/\\/g, '/');

    if (!isSafeEntryName(entryName)) {
      throw new ValidationError(`Unsafe path in archive: ${entryName}`);
    }

    const parts = entryName.split('/').filter(Boolean);
    const topLevel = parts[0] ? parts[0].toLowerCase() : '';

    if (FORBIDDEN_TOP_LEVEL.has(topLevel)) {
      throw new ValidationError(
        `Archive already contains "${parts[0]}". Upload a plain React project — native platform folders are generated by the build.`
      );
    }

    if (entryName === 'package.json' || entryName.endsWith('/package.json')) {
      // Only trust a package.json at the project root (depth 0 or 1 if the
      // zip wraps everything in a single top folder).
      if (parts.length <= 2) hasPackageJson = true;
    }

    if (!entry.isDirectory) {
      const ext = path.extname(entryName).toLowerCase();
      if (ext && !ALLOWED_EXTENSIONS.has(ext)) {
        throw new ValidationError(`Disallowed file type in archive: ${entryName}`);
      }
    }
  }

  if (!hasPackageJson) {
    throw new ValidationError('No package.json found at the project root.');
  }

  fs.mkdirSync(destDir, { recursive: true });
  zip.extractAllTo(destDir, true);

  // If the zip wrapped everything in a single top-level folder, flatten it
  // so package.json ends up directly inside destDir.
  const rootEntries = fs.readdirSync(destDir);
  if (rootEntries.length === 1) {
    const onlyPath = path.join(destDir, rootEntries[0]);
    if (fs.statSync(onlyPath).isDirectory() && fs.existsSync(path.join(onlyPath, 'package.json'))) {
      for (const child of fs.readdirSync(onlyPath)) {
        fs.renameSync(path.join(onlyPath, child), path.join(destDir, child));
      }
      fs.rmSync(onlyPath, { recursive: true, force: true });
    }
  }

  if (!fs.existsSync(path.join(destDir, 'package.json'))) {
    throw new ValidationError('package.json not found after extraction.');
  }
}

module.exports = { validateAndExtract, ValidationError };
