import { useState } from 'react';

export default function StructureGuide() {
  const [open, setOpen] = useState(false);

  return (
    <div className="guide">
      <button type="button" className="guide-toggle" onClick={() => setOpen((o) => !o)} aria-expanded={open}>
        <span className={`log-toggle-caret${open ? ' open' : ''}`} aria-hidden="true">▸</span>
        Project structure guide
      </button>

      {open && (
        <div className="guide-body">
          <div className="guide-grid">
            <div className="guide-card">
              <div className="guide-card-title">
                <span className="guide-dot guide-dot-teal" />
                Web / Capacitor project
              </div>
              <ul className="guide-list">
                <li><code>package.json</code> at the archive root</li>
                <li>No <code>android/</code>, <code>ios/</code>, or <code>platforms/</code> folder — those are generated by the build</li>
                <li>A <code>capacitor.config.json/.ts</code> is optional — reused if present, created if not</li>
              </ul>
            </div>

            <div className="guide-card">
              <div className="guide-card-title">
                <span className="guide-dot guide-dot-copper" />
                Native Android project
              </div>
              <ul className="guide-list">
                <li><code>settings.gradle</code> (or <code>.kts</code>) and a root <code>build.gradle</code> (or <code>.kts</code>)</li>
                <li>The complete Gradle wrapper: <code>gradlew</code>, <code>gradlew.bat</code>, <code>gradle/wrapper/gradle-wrapper.jar</code>, <code>gradle/wrapper/gradle-wrapper.properties</code></li>
                <li>Run <code>gradle wrapper</code> before zipping if any of those are missing</li>
              </ul>
            </div>
          </div>

          <div className="guide-row">
            <div className="guide-row-label">Archive rules</div>
            <ul className="guide-list">
              <li>One project per <code>.zip</code>, up to 300&nbsp;MB — several archives can be dropped at once</li>
              <li>A single top-level wrapper folder (e.g. <code>my-app/</code>) is fine — it's auto-flattened</li>
              <li>Path traversal, absolute paths, and null bytes in entry names are rejected outright</li>
            </ul>
          </div>

          <div className="guide-row">
            <div className="guide-row-label">Allowed file types</div>
            <p className="guide-note">
              Anything else (editor/OS cruft, license files, unrecognized binaries) is silently skipped rather
              than failing the upload — you'll see what got left out in the build log.
            </p>
            <div className="guide-chips">
              {['.js/.jsx/.ts/.tsx', '.json/.yml/.lock', '.css/.scss/.less', '.html/.md/.txt', '.png/.jpg/.svg/.webp', '.woff/.ttf', '.mp4/.mp3/.pdf', '.kt/.java/.gradle', '.xml/.aidl/.pro'].map((c) => (
                <span key={c} className="guide-chip">{c}</span>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
