import { useEffect, useRef, useState } from 'react';
import FileTree from './FileTree.jsx';
import { readZipStructure } from '../lib/zipTree.js';

const PROJECT_TYPE_LABEL = {
  'capacitor-web': 'Web project (Capacitor)',
  'native-android': 'Native Android (Gradle)',
};

// Reads the archive entirely in the browser — no upload round-trip needed
// just to see what's inside it. Opens itself automatically the first time
// a tree is ready (so the person sees it without an extra click), then
// behaves like a normal collapsible section after that.
export default function StructurePanel({ file, onDetected, onExpand }) {
  const [state, setState] = useState({ status: 'reading' });
  const [open, setOpen] = useState(false);
  const [autoOpened, setAutoOpened] = useState(false);
  const expandFired = useRef(false);

  useEffect(() => {
    let cancelled = false;
    setState({ status: 'reading' });
    readZipStructure(file)
      .then((result) => {
        if (cancelled) return;
        setState({ status: 'ready', ...result });
        setOpen(true);
        setAutoOpened(true);
        onDetected?.(result.projectType);
        if (!expandFired.current) {
          expandFired.current = true;
          onExpand?.();
        }
      })
      .catch((err) => {
        if (cancelled) return;
        setState({ status: 'error', message: err?.message || 'Could not read this archive.' });
      });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [file]);

  function toggleOpen() {
    setOpen((o) => {
      const next = !o;
      if (next && !expandFired.current) {
        expandFired.current = true;
        onExpand?.();
      }
      return next;
    });
  }

  if (state.status === 'reading') {
    return (
      <div className="structure-panel structure-loading" aria-live="polite">
        <span className="structure-spinner" aria-hidden="true" />
        Reading archive structure…
      </div>
    );
  }

  if (state.status === 'error') {
    return (
      <div className="structure-panel structure-error">
        Couldn't preview the archive structure: {state.message}
      </div>
    );
  }

  const { tree, fileCount, skippedCount, projectType, forbiddenFolder, wrapperComplete, missingWrapper } = state;
  const problem = forbiddenFolder || (projectType === null) || !wrapperComplete;

  return (
    <div className={`structure-panel${autoOpened ? ' structure-fresh' : ''}`}>
      <button
        type="button"
        className="structure-toggle"
        onClick={toggleOpen}
        aria-expanded={open}
      >
        <span className={`log-toggle-caret${open ? ' open' : ''}`} aria-hidden="true">▸</span>
        Project structure
        <span className="structure-count">{fileCount} file{fileCount === 1 ? '' : 's'}</span>
        {projectType && <span className="structure-type">{PROJECT_TYPE_LABEL[projectType]}</span>}
        {problem && <span className="structure-warn-dot" aria-hidden="true" title="Needs attention" />}
      </button>

      <div className={`structure-body-wrap${open ? ' open' : ''}`}>
        <div className="structure-body">
          <div className="structure-body-inner">
            {forbiddenFolder && (
              <div className="structure-alert">
                Contains a top-level <code>{forbiddenFolder}/</code> folder — that's generated by the
                build itself and will be rejected. Remove it and re-zip.
              </div>
            )}
            {!forbiddenFolder && projectType === null && (
              <div className="structure-alert">
                No <code>package.json</code> or <code>settings.gradle</code> found at the project
                root — the build worker won't be able to detect a project type.
              </div>
            )}
            {!forbiddenFolder && projectType === 'native-android' && !wrapperComplete && (
              <div className="structure-alert">
                Missing Gradle wrapper file{missingWrapper.length === 1 ? '' : 's'}:{' '}
                {missingWrapper.map((m) => <code key={m}>{m}</code>).reduce((a, b) => [a, ', ', b])}. Run{' '}
                <code>gradle wrapper</code> and re-zip.
              </div>
            )}
            {skippedCount > 0 && (
              <div className="structure-note">
                {skippedCount} file{skippedCount === 1 ? '' : 's'} outside the allowed types will be
                skipped on upload — shown in the tree below.
              </div>
            )}
            <div className="file-tree-scroll">
              <FileTree nodes={tree} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
